steps = [
    [
        # Up
        """--sql
            INSERT INTO genres_movies (
                        movie_id,
                        genre_id
            )
            VALUES
            (
                1,
                2
            ),
            (
                1,
                1
            ),
            (
                1,
                15
            ),
            (
                2,
                2
            ),
            (
                2,
                1
            ),
            (
                2,
                15
            ),
            (
                3,
                2
            ),
            (
                3,
                1
            ),
            (
                3,
                15
            )
        """,
        # Down
        """
        """,
    ]
]
